language: node_js
node_js:
  - "14"
  - "18"

branches:
  only:
    - master
    - production

script:
  - echo '-> ------------- Starting nodecache.js Build -------------'
  - echo '-> Installing Dependencies...'
  - npm install
  - echo '-> Running Unit Tests...'
  - npm test

# Skip builds for pull requests
pull_request: false