name: Unit Test Coverage
on:
    pull_request:
        branches:
            - master
            - publish
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                custom-title: Jest Coverage report for NodeCache